### ISSUE TITLE
Class WebSocketServer is missing when spinning up an OSCQuery server

### ISSUE THREAD

**Issue by capital-G** [OSSIA/ossia-sclang#1]
After installing the Quark in SC 3.10.4 and following the provided guide

https://github.com/ossia/ossia-sclang/blob/1d2913c18d6ffc1279751ee8bab312e80441022a/HelpSource/Guides/OssiaReference.schelp#L26-L27

one will face the error

```
Execution warning: Class 'WebSocketServer' not found
ERROR: Message 'new' not understood.
```

which is caused by

https://github.com/ossia/ossia-sclang/blob/1d2913c18d6ffc1279751ee8bab312e80441022a/classes/OssiaProtocols.sc#L130

Following [the original repo](https://github.com/OSSIA/ossia-supercollider) it seems that [a server was provided as a primitive within SuperCollider](https://github.com/ossia/ossia-supercollider/blob/master/Ossia/Primitives/pyrossiaprim.cpp#L393).

It seems SuperCollider is really lacking network capabilities (at least myself is writing python wrapper for network functionalities all the time) and maybe it is best to implement network capabilities once properly with a Quark so one can start and poll web servers from within SuperCollider?

**Comment by thibaudk** [comment]
Hi @capital-G 

Very sorry, I didn't see this issue.
I realize that it was made prior to our conversation on 
https://github.com/supercollider/supercollider/issues/5310

Was the issue cleared up by our discussion ?
you need either
https://github.com/pchdev/wsclang
or
https://github.com/scrime-u-bordeaux/supercollider
for oscquery

**Comment by capital-G** [comment]
Yes - cleared up :)

**Comment by thibaudk** [comment]
cool, we'll continue the discussion on
 supercollider/supercollider#5310
